steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_IMAGE}:latest",
        "-t",
        "${_IMAGE}:${_CI_BUILD_ID}",
        "--build-arg",
        "package=${_PACKAGE}",
        ".",
      ]
images: ["${_IMAGE}:latest", "${_IMAGE}:${_CI_BUILD_ID}"]
