apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-creators-deployment
  labels:
    app: character-creators
spec:
  replicas: 2
  selector:
    matchLabels:
      app: character-creators
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: character-creators
    spec:
      containers:
        - name: character-creators
          image: gcr.io/marvel-2-288009/character-creators
          imagePullPolicy: Always
          ports:
            - containerPort: 3200
