apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvel-comics-cron-deployment
  labels:
    app: marvel-comics-cron
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marvel-comics-cron
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: marvel-comics-cron
    spec:
      containers:
        - name: marvel-comics-cron
          image: gcr.io/marvel-2-288009/marvel-comics-cron
          imagePullPolicy: Always
          ports:
            - containerPort: 3200
