apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-character-creators-deployment
  labels:
    app: search-character-creators
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-character-creators
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: search-character-creators
    spec:
      containers:
        - name: search-character-creators
          image: gcr.io/marvel-2-288009/search-character-creators/prod
          imagePullPolicy: Always
          ports:
            - containerPort: 3200
