apiVersion: v1
kind: Service
metadata:
  name: sigein-frontend-service
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 80
      nodePort: 31515
      protocol: TCP
      name: http
  selector:
    app: sigein-frontend
