apiVersion: v1
kind: Service
metadata:
  name: web-gateway-service
spec:
  type: NodePort
  ports:
    - port: 3060
      targetPort: 3200
      nodePort: 32020
      protocol: TCP
      name: http
  selector:
    app: web-gateway
