name: Deploy Marvel service
on:
  push:
    tags:
      - character-interactions@*
      - characters-creators@*
      - marvel-comics-cron@*
      - search-character-creators@*
      - search-character-interactions@*
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: docker://google/cloud-sdk:latest
      - run: echo $GITHUB_REF
      - run: IFS='/@' read -ra REF_ARRAY <<< "$GITHUB_REF"
      - run: APP="${REF_ARRAY[2]}"
      - run: CONTAINER_IMAGE_PROD=gcr.io/"${{ secrets.GCLOUD_PROJECT_ID }}"/$APP/prod
      - run: touch $GITHUB_WORKSPACE/sa.json
      - run: echo ${{ secrets.DEPLOY_KEY }} > $GITHUB_WORKSPACE/sa.json
      - run: cat $GITHUB_WORKSPACE/sa.json
      - run: export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/sa.json
      - run: gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/sa.json
      - run: gcloud config set project "${{ secrets.GCLOUD_PROJECT_ID }}"
      - run: gcloud config set compute/zone "${{ secrets.CLOUDSDK_ZONE }}"
      - run: gcloud builds submit --config cloudbuild.yml --substitutions _IMAGE=$GITHUB_REF,_CI_BUILD_ID=$GITHUB_RUN_ID,_CLOUDSDK_COMPUTE_ZONE="${{ secrets.CLOUDSDK_ZONE }}",_CLOUDSDK_CONTAINER_CLUSTER="${{ secrets.CONTAINER_CLUSTER }}",_KUBECTL_ENV=production,_APP=$APP,_CONTAINER_IMAGE=$CONTAINER_IMAGE_PROD,_CI_BUILD_ID=$CI_BUILD_ID,_PACKAGE=$APP --timeout="1h" .
