name: Deploy Marvel service
on:
  push:
    tags:
      - character-interactions@*
      - characters-creators@*
      - marvel-comics-cron@*
      - search-character-creators@*
      - search-character-interactions@*
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.DEPLOY_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: export CLOUDSDK_ZONE=${{ secrets.CLOUDSDK_ZONE }}
      - run: export CONTAINER_CLUSTER=${{ secrets.CONTAINER_CLUSTER }}
      - run: export GCLOUD_PROJECT_ID=${{ secrets.GCLOUD_PROJECT_ID }}
      - run: echo $GITHUB_REF
      - run: IFS='/@' read -ra REF_ARRAY <<< "$GITHUB_REF"
      - run: APP="${REF_ARRAY[2]}"
      - run: CONTAINER_IMAGE_PROD=gcr.io/$GCLOUD_PROJECT_ID/$APP/prod
      - run: gcloud config set project $INPUT_GCLOUD_PROJECT_ID
      - run: gcloud config set compute/zone $INPUT_CLOUDSDK_ZONE
      - run: gcloud builds submit --config cloudbuild.yml --substitutions _IMAGE=$GITHUB_REF,_CI_BUILD_ID=$GITHUB_RUN_ID,_CLOUDSDK_COMPUTE_ZONE=$INPUT_CLOUDSDK_ZONE,_CLOUDSDK_CONTAINER_CLUSTER=$INPUT_CONTAINER_CLUSTER,_KUBECTL_ENV=production,_APP=$APP,_CONTAINER_IMAGE=$CONTAINER_IMAGE_PROD,_CI_BUILD_ID=$CI_BUILD_ID,_PACKAGE=$APP --timeout="1h" .
