name: Deploy Marvel service
on:
  push:
    tags:
      - character-interactions@*
      - characters-creators@*
      - marvel-comics-cron@*
      - search-character-creators@*
      - search-character-interactions@*
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My first step
        uses: GoogleCloudPlatform/github-actions@0.1.2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.DEPLOY_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: echo $GITHUB_REF
      - run: IFS='/@' read -ra REF_ARRAY <<< "$GITHUB_REF"
      - run: export APP="${REF_ARRAY[2]}"
      - run: export CONTAINER_IMAGE_PROD=gcr.io/marvel-287923/$APP/prod
      - run: echo $CONTAINER_IMAGE_PROD
      - run: gcloud config set project marvel-287923
      - run: gcloud config set compute/zone us-central1-a
      - run: gcloud builds submit --config $GITHUB_WORKSPACE/cloudbuild.yml --substitutions _IMAGE=$CONTAINER_IMAGE_PROD,_CI_BUILD_ID=$GITHUB_RUN_ID,_CLOUDSDK_COMPUTE_ZONE=us-central1-a,_CLOUDSDK_CONTAINER_CLUSTER=sigepin-cluster,_KUBECTL_ENV=production,_APP=$APP,_CONTAINER_IMAGE=$CONTAINER_IMAGE_PROD,_CI_BUILD_ID=$CI_BUILD_ID,_PACKAGE=$APP --timeout="1h" .
